# Generated by Django 4.2.6 on 2023-12-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20231026_1221'),
        ('user_registered', '0003_alter_favoritebook_book_delete_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritebook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='favoritebook',
            name='user',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.AddField(
            model_name='profile',
            name='buku',
            field=models.ManyToManyField(to='book.book'),
        ),
        migrations.DeleteModel(
            name='FavoriteBook',
        ),
    ]
