# Generated by Django 4.2.6 on 2023-12-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_registered', '0004_remove_favoritebook_book_remove_favoritebook_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='buku',
            new_name='favorite_books',
        ),
    ]
