# Generated by Django 4.2.6 on 2023-12-12 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_registered', '0006_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
